name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]
        maven: [ 3.8.1, 3.9.0 ]

    name: Java ${{ matrix.java }}, Maven ${{ matrix.maven }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Set up Maven ${{ matrix.maven }}
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: ${{ matrix.maven }}
      - name: Run tests
        run: mvn test integration-test
